// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mis_mmc.Models;

#nullable disable

namespace mis_mmc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220403083202_faculty")]
    partial class faculty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mis_mmc.Models.CollegeDetails", b =>
                {
                    b.Property<int>("s_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("college_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("phone_number_one")
                        .HasColumnType("int");

                    b.HasKey("s_no");

                    b.ToTable("CollegeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
